language: python
python:
  - "3.7"
install:
  - pipenv install --dev
script:
  - pipenv run mypy --strict *.py
  - pipenv run pylint --init-hook="import sys; sys.setrecursionlimit(2000)" -d missing-docstring,bad-continuation,line-too-long,invalid-name *.py
