name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Pipenv
      run: pip3 install pipenv && python3 --version && pip3 --version && pipenv --version
    - name: Cache Pipenv virtualenv
      uses: actions/cache@v1.1.0
      with:
        # A directory to store and save the cache
        path: $HOME/.local/share/virtualenvs/
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    - name: Install dependencies
      run: pipenv install --dev
    - name: mypy
      run: pipenv run mypy . test
    - name: pylint
      run: pipenv run pylint *.py test/*.py
    - name: pytest
      run: pipenv run python -m pytest --cov=. --cov-report term-missing -r f --disable-warnings test/
