name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Pipenv
      run: pip install --upgrade pip && pip install pipenv ; python --version ; pip --version ; pipenv --version
    - name: mypy
      run: pipenv run mypy . test
    - name: pylint
      run: pipenv run pylint *.py test/*.py
    - name: pytest
      run: python -m pytest --cov=. --cov-report term-missing -r f --disable-warnings test/
