name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Pipenv
      run: pip3 install pipenv && python3 --version && pip3 --version && pipenv --version
    - name: mypy
      run: pipenv run mypy . test
    - name: pylint
      run: pipenv run pylint *.py test/*.py
    - name: pytest
      run: python -m pytest --cov=. --cov-report term-missing -r f --disable-warnings test/
